package com.secretpackage.inspector.util;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by ali on 7/10/19.
 */

public class Constants {

    static public Map<String, String> Visit_values = new LinkedHashMap<>();
    static public Map<String, String> Utility_values = new LinkedHashMap<>();

//    static public Map<String, String> Property_type_res_values = new LinkedHashMap<>();
//    static public Map<String, String> Property_type_com_values = new LinkedHashMap<>();
//    static public Map<String, String> Property_type_vac_values = new LinkedHashMap<>();

    static public Map<String, String> Occu_code_values = new LinkedHashMap<>();
    static public Map<String, String> Occu_values = new LinkedHashMap<>();
    static public Map<String, String> Location_values = new LinkedHashMap<>();
    static public Map<String, String> Topology_values = new LinkedHashMap<>();

    static public Map<String, String> Style_res_values = new LinkedHashMap<>();
    static public Map<String, String> Style_com_values = new LinkedHashMap<>();
    static public Map<String, String> Grade_values = new LinkedHashMap<>();
    static public Map<String, String> Depreciation_values = new LinkedHashMap<>();
//    static public Map<String, String> Story_values = new LinkedHashMap<>();
    static public Map<String, String> Roof_Structure_values = new LinkedHashMap<>();
    static public Map<String, String> Roof_Cover_values = new LinkedHashMap<>();
    static public Map<String, String> Heat_Type_values = new LinkedHashMap<>();
    static public Map<String, String> Fuel_Type_values = new LinkedHashMap<>();
    static public Map<String, String> AC_Type_values = new LinkedHashMap<>();
    static public Map<String, String> Int_Wall_values = new LinkedHashMap<>();
    static public Map<String, String> Int_Floor_values = new LinkedHashMap<>();
    static public Map<String, String> Ext_Wall_res_values = new LinkedHashMap<>();
    static public Map<String, String> Feature_res_values = new LinkedHashMap<>();
    static public Map<String, String> Feature_com_values = new LinkedHashMap<>();
    static public Map<String, String> Feature_cond_values = new LinkedHashMap<>();

    static public Map<String, String> Ext_Wall_com_values = new LinkedHashMap<>();
    static public Map<String, String> Biz_type_com_values = new LinkedHashMap<>();
    static public Map<String, String> Ceiling_com_values = new LinkedHashMap<>();

    static public Map<String, String> Kitchen_values = new LinkedHashMap<>();
    static public Map<String, String> Bath_values = new LinkedHashMap<>();
    static public Map<String, String> Floor_values = new LinkedHashMap<>();

    static public final int PROP_RESIDENTIAL = 0;
    static public final int PROP_COMMERCIAL = 1;
    static public final int PROP_CONDO = 2;
    static public final int PROP_VACANT = 3;

    static public final int PROP_SFR = 4;
    static public final int PROP_AGRIC = 5;
    static public final int PROP_COMM = 6;
    static public final int PROP_MULTRES = 7;

    static public final String[] prop_types = new String[]{"Res", "Comm", "Condo", "Vacant", "SFR", "AGRIC", "COMM", "MULTR"};

    public static void init() {

        Visit_values.put("", "NONE");
        Visit_values.put("00", "Site Visit-Full Measure and List");
        Visit_values.put("01", "Site Visit-Exterior Only");
        Visit_values.put("02", "Site Visit-Interior Only");
        Visit_values.put("03", "Desktop Review");
        Visit_values.put("04", "Interview with Property Owner");
        Visit_values.put("05", "Drive-By");
        Visit_values.put("07", "Inspection Denied by Property Owner");
        Visit_values.put("08", "Callback Notice Left");
        Visit_values.put("51", "Building Permit");

//        Property_type_res_values.put("01", "Residential");
//        Property_type_res_values.put("04", "Condo Main");
//        Property_type_res_values.put("05", "Res Condo");
//
//        Property_type_com_values.put("06", "Com Condo");
//        Property_type_com_values.put("94", "Commercial");
//        Property_type_com_values.put("95", "Gar/Svc Statn");
//        Property_type_com_values.put("96", "Industrial");
//
//        Property_type_vac_values.put("00", "Vacant");

        Utility_values.put("", "NONE");


        Utility_values.put("1", "All Public");
        Utility_values.put("2", "Public Water");
        Utility_values.put("3", "Public Sewer");
        Utility_values.put("4", "Gas");
        Utility_values.put("5", "Well");
        Utility_values.put("6", "Septic");

        Occu_code_values.put("", "NONE");
        Occu_code_values.put("013C", "PRI RES MDL-94");
        Occu_code_values.put("111C", "APT 4-8 MDL 94");
        Occu_code_values.put("130", "PRI RES COM");
        Occu_code_values.put("303A", "ACC COM LND");
        Occu_code_values.put("310", "PRI COMM");
        Occu_code_values.put("424V", "ELECSUBSTA  MDL-00");
        Occu_code_values.put("995", "CONDO MAIN");
        Occu_code_values.put("996", "CONDOMAIN");
        Occu_code_values.put("900R", "US GOVT");
        Occu_code_values.put("900V", "US GOVT MDL-00");
        Occu_code_values.put("903C", "MUNICPAL  MDL-94");
        Occu_code_values.put("903V", "MUNICIPAL MDL-00");
        Occu_code_values.put("904C", "PRI SCHOOL  MDL-94");
        Occu_code_values.put("905V", "P/HOS CHAR  MDL-00");
        Occu_code_values.put("906C", "CHURCH ETC  MDL-94");
        Occu_code_values.put("909R", "RELIGIOUS  MDL-01");
        Occu_code_values.put("910C", "CHARITABLE  MDL-94");
        Occu_code_values.put("910M", "EX CONDO  MDL-06");
        Occu_code_values.put("910V", "COMM MASS DEM");
        Occu_code_values.put("920C", "NON PROFIT  MDL-94");
        Occu_code_values.put("920V", "NON PROFIT  MDL-00");
        Occu_code_values.put("922C", "MASS. MILITARY");
        Occu_code_values.put("922I", "MASS MILITARY");
        Occu_code_values.put("922V", "MASS MILITARY");
        Occu_code_values.put("924V", "NON PROFIT");
        Occu_code_values.put("925C", "COMM MASS MDC");
        Occu_code_values.put("925I", "COMM MASS MDC");
        Occu_code_values.put("925V", "COMM MASS MDC");
        Occu_code_values.put("928V", "COMM MASS CAP PLAN");
        Occu_code_values.put("930C", "COMM MASS MBTA");
        Occu_code_values.put("930V", "MUNICIPAL MDL00");
        Occu_code_values.put("931C", "IMPROV LAND CITY");
        Occu_code_values.put("931I", "IMPROV MDL 96");
        Occu_code_values.put("931R", "MUNIC IMPRO MDL 01");
        Occu_code_values.put("931V", "MUNICIPAL");
        Occu_code_values.put("933V", "VAC EDUCATION");
        Occu_code_values.put("934C", "IMPR EDUCATION");
        Occu_code_values.put("934I", "IMP EDUCATION");
        Occu_code_values.put("934V", "VAC EDU");
        Occu_code_values.put("935I", "IMP PUBLIC SAFETY");
        Occu_code_values.put("936V", "TAX TITLE VAC");
        Occu_code_values.put("939C", "IMPRO CNTY");
        Occu_code_values.put("940C", "PRIV ELEM");
        Occu_code_values.put("941C", "PRIV SEC LVL");
        Occu_code_values.put("942R", "PRIV COLL");
        Occu_code_values.put("942V", "VAC PRIV COL");
        Occu_code_values.put("953C", "CEMETERY IMP");
        Occu_code_values.put("953V", "CEMETERY");
        Occu_code_values.put("954C", "FRAT/FUNC");
        Occu_code_values.put("954R", "COMM CTR");
        Occu_code_values.put("955C", "HOSP");
        Occu_code_values.put("956C", "LIBRARY MDL 94");
        Occu_code_values.put("956R", "LIBRARY RES");
        Occu_code_values.put("956V", "LIBRARY VAC");
        Occu_code_values.put("957C", "CHAR SERV COM");
        Occu_code_values.put("957I", "CHAR SERV IN");
        Occu_code_values.put("957R", "CHAR SERV");
        Occu_code_values.put("957U", "CHAR SER");
        Occu_code_values.put("957V", "CHAR SERV VAC");
        Occu_code_values.put("959C", "HSING");
        Occu_code_values.put("959R", "HSING");
        Occu_code_values.put("960C", "CHURCH");
        Occu_code_values.put("960I", "CHURCH");
        Occu_code_values.put("960R", "CHURCH");
        Occu_code_values.put("960V", "CHURCH VAC");
        Occu_code_values.put("961C", "RECTORY");
        Occu_code_values.put("961R", "RECTORY");
        Occu_code_values.put("962C", "OTHER RELIG");
        Occu_code_values.put("962R", "RELIG RES");
        Occu_code_values.put("962V", "RELIG VAC");
        Occu_code_values.put("970C", "HSING ATHORITY");
        Occu_code_values.put("970R", "HSING AUTH");
        Occu_code_values.put("970V", "HSING AUTH MDL 00");
        Occu_code_values.put("972C", "TRANS AUTH");
        Occu_code_values.put("972I", "TRANS AUTH");
        Occu_code_values.put("972V", "TRANS AUTH");
        Occu_code_values.put("985C", "OTHER CITY");
        Occu_code_values.put("985I", "OTHER CITY");
        Occu_code_values.put("990C", "121A CORP");
        Occu_code_values.put("990I", "121A CORP");
        Occu_code_values.put("1010", "Single Fam  MDL-01");
        Occu_code_values.put("1012", "OCN FT");
        Occu_code_values.put("1015", "SINGLE FAM IN LAW");
        Occu_code_values.put("1016", "ONE FAMILY W/DAYCARE");
        Occu_code_values.put("1021", "Condo NL  MDL-05");
        Occu_code_values.put("1040", "TWO FAMILY");
        Occu_code_values.put("1045", "TWO FAM IN LAW");
        Occu_code_values.put("1050", "THREE FAM");
        Occu_code_values.put("1060", "AC LND IMP");
        Occu_code_values.put("1090", "MULTI HSES  MDL-03");
        Occu_code_values.put("1110", "APT 4-8 UNT");
        Occu_code_values.put("1120", "APT OVER 8");
        Occu_code_values.put("1210", "BOARDNG HS");
        Occu_code_values.put("1250", "OTHR LIV F");
        Occu_code_values.put("1300", "RES ACLNDV  MDL-00");
        Occu_code_values.put("1310", "RES ACLNPO");
        Occu_code_values.put("1320", "RES ACLNUD");
        Occu_code_values.put("1400", "CHILD CARE");
        Occu_code_values.put("3000", "HOTELS");
        Occu_code_values.put("3010", "MOTELS");
        Occu_code_values.put("3040", "NURSING HM");
        Occu_code_values.put("3050", "HOSP PVT");
        Occu_code_values.put("3100", "RTL OIL ST");
        Occu_code_values.put("3150", "DOCKYARDS");
        Occu_code_values.put("3160", "COMM WHSE");
        Occu_code_values.put("3180", "COM GRN HS");
        Occu_code_values.put("3210", "HRDWARE ST");
        Occu_code_values.put("3220", "STRIP STORES");
        Occu_code_values.put("3221", "RTL CONDO");
        Occu_code_values.put("3222", "COMM BLDG");
        Occu_code_values.put("3230", "SHOPNG CTR");
        Occu_code_values.put("3240", "SUPERMKT");
        Occu_code_values.put("3250", "RETAIL");
        Occu_code_values.put("3260", "REST/CLUBS");
        Occu_code_values.put("3300", "AUTO DEALER");
        Occu_code_values.put("3320", "AUTO REPR/GAR");
        Occu_code_values.put("3330", "FUEL SV/PR");
        Occu_code_values.put("3340", "GAS ST SRV  MDL-95");
        Occu_code_values.put("3350", "CAR WASH  MDL-95");
        Occu_code_values.put("3360", "PARK GAR");
        Occu_code_values.put("3370", "PARK LOT");
        Occu_code_values.put("3380", "OTH MTR SS");
        Occu_code_values.put("3390", "GAS MART");
        Occu_code_values.put("3400", "OFFICE BLD");
        Occu_code_values.put("3401", "OFF CONDO  MDL-06");
        Occu_code_values.put("3402", "OFFICEBLDG");
        Occu_code_values.put("3410", "BANK BLDG");
        Occu_code_values.put("3420", "MED OFFC");
        Occu_code_values.put("3430", "PROF OFFC");
        Occu_code_values.put("3500", "POST OFF");
        Occu_code_values.put("3510", "EDUC BLDG");
        Occu_code_values.put("3530", "FRATNL ORG");
        Occu_code_values.put("3550", "FUNERAL HM");
        Occu_code_values.put("3560", "PROF ASSOC");
        Occu_code_values.put("3640", "THEATER");
        Occu_code_values.put("3700", "BOWLING");
        Occu_code_values.put("3740", "HEALTH SPA");
        Occu_code_values.put("3760", "GYMS");
        Occu_code_values.put("3800", "GOLF CRSE");
        Occu_code_values.put("3810", "TENNIS ODR");
        Occu_code_values.put("3840", "MARINAS");
        Occu_code_values.put("3880", "OTHR OUTDR");
        Occu_code_values.put("3900", "DEVEL LAND");
        Occu_code_values.put("3910", "POT DEVEL");
        Occu_code_values.put("3920", "UNDEV LAND");
        Occu_code_values.put("4000", "INDUSTRIAL");
        Occu_code_values.put("4010", "IND WHSES  MDL-96");
        Occu_code_values.put("4020", "IND OFFICE");
        Occu_code_values.put("4021", "IND CONDO  MDL-06");
        Occu_code_values.put("4022", "IND BLDG");
        Occu_code_values.put("4030", "ACCLND MFG");
        Occu_code_values.put("4240", "ELECSUBSTA");
        Occu_code_values.put("4300", "TEL X STA");
        Occu_code_values.put("4310", "TEL REL TW");
        Occu_code_values.put("4330", "RAD/TV TR  MDL-96");
        Occu_code_values.put("4400", "IND LD DV");
        Occu_code_values.put("4410", "IND LD PO");
        Occu_code_values.put("4420", "IND LD UD");
        Occu_code_values.put("9000", "US GOVT MDL-94");
        Occu_code_values.put("9010", "COMM-MASS");
        Occu_code_values.put("9037", "PUB-SCHOOL  MDL-94");
        Occu_code_values.put("9100", "DEPT.ENVIRON.MANGMT");
        Occu_code_values.put("9140", "COMM MASS DMH");
        Occu_code_values.put("9420", "PRIV COLL/UNIV");
        Occu_code_values.put("9540", "FRAT/HALLS IND");
        Occu_code_values.put("9580", "RECREATION");
        Occu_code_values.put("9950", "OTHER OPEN SP");
        Occu_code_values.put("9970", "OTHER");

        Occu_values.put("", "NONE");
        Occu_values.put("1", "");
        Occu_values.put("2", "");
        Occu_values.put("3", "");
        Occu_values.put("4", "");
        Occu_values.put("5", "");
        Occu_values.put("6", "");
        Occu_values.put("7", "");
        Occu_values.put("8", "");
        Occu_values.put("9", "");
        Occu_values.put("10", "");
        Occu_values.put("10+", "");

        Depreciation_values.put("", "NONE");
        Depreciation_values.put("E", "Excellent");
        Depreciation_values.put("VG", "Very Good");
        Depreciation_values.put("G", "Good");
        Depreciation_values.put("A", "Average");
        Depreciation_values.put("F", "Fair");
        Depreciation_values.put("P", "Poor");
        Depreciation_values.put("VP", "Very Poor");

        Location_values.put("", "NONE");
        Location_values.put("1", "Urban");
        Location_values.put("2", "Suburban");
        Location_values.put("3", "Rural");
        Location_values.put("4", "Business District");
        Location_values.put("5", "Industrial");
        Location_values.put("6", "Recreational");
        Location_values.put("7", "Waterfront");
        Location_values.put("8", "Flood Plain");
        Location_values.put("9", "Town Line");

        Topology_values.put("", "NONE");
        Topology_values.put("1", "Level");
        Topology_values.put("2", "High");
        Topology_values.put("3", "Low");
        Topology_values.put("4", "Rolling");
        Topology_values.put("5", "Wetland");
        Topology_values.put("6", "Waterfront");
        Topology_values.put("7", "Waterview");
        Topology_values.put("8", "View");
        Topology_values.put("9", "Steep");

        Style_res_values.put("", "NONE");
        Style_res_values.put("00", "3 Fam Flat");
        Style_res_values.put("01", "Ranch");
        Style_res_values.put("02", "Split Level");
        Style_res_values.put("03", "Colonial");
        Style_res_values.put("04", "Cape Cod");
        Style_res_values.put("4F", "4 FAM");
        Style_res_values.put("05", "Bungalow");
        Style_res_values.put("06", "Conventional");
        Style_res_values.put("07", "Modern/Contemp");
        Style_res_values.put("08", "Raised Ranch");
        Style_res_values.put("09", "2 Fam Flat");
        Style_res_values.put("10", "Family Duplex");
        Style_res_values.put("11", "2 Fam Conver");
        Style_res_values.put("14", "Apartments");
        Style_res_values.put("20", "Quincy Cape");
        Style_res_values.put("44", "Tudor");
        Style_res_values.put("45", "3 Fam Conv");
        Style_res_values.put("63", "Antique");
        Style_res_values.put("94", "Outbuildings");

        Style_com_values.put("", "NONE");
        Style_com_values.put("12", "Commercial");
        Style_com_values.put("13", "Department Str");
        Style_com_values.put("14", "Apartments");
        Style_com_values.put("15", "STRIP STORES");
        Style_com_values.put("16", "PLAZA");
        Style_com_values.put("17", "Store");
        Style_com_values.put("18", "Office Bldg");
        Style_com_values.put("19", "Profess. Bldg");
        Style_com_values.put("20", "Quincy Cape");
        Style_com_values.put("21", "Fast Food Rest");
        Style_com_values.put("22", "Supermarket");
        Style_com_values.put("23", "Finan Inst.");
        Style_com_values.put("24", "Child/Daycare");
        Style_com_values.put("25", "Serv Shop/GAR");
        Style_com_values.put("26", "GAS STATION");
        Style_com_values.put("27", "Auto DEALER");
        Style_com_values.put("28", "Funeral Home");
        Style_com_values.put("29", "Nursing Home");
        Style_com_values.put("30", "Restaurant");
        Style_com_values.put("31", "Bank");
        Style_com_values.put("32", "Theaters Encl.");
        Style_com_values.put("33", "VET CLINIC");
        Style_com_values.put("34", "Bowling/Arena");
        Style_com_values.put("35", "Apt Gar");
        Style_com_values.put("36", "Camp");
        Style_com_values.put("37", "Quonset Bldg");
        Style_com_values.put("38", "Country Club");
        Style_com_values.put("39", "Motel");
        Style_com_values.put("40", "INDUSTRIAL");
        Style_com_values.put("41", "Research/Devel");
        Style_com_values.put("42", "MILL BLDG");
        Style_com_values.put("43", "Car Wash");
        Style_com_values.put("44", "Tudor");
        Style_com_values.put("45", "3 Fam Conv");
        Style_com_values.put("46", "Food Process");
        Style_com_values.put("47", "Cold Storage");
        Style_com_values.put("48", "Warehouse");
        Style_com_values.put("49", "MED PROF BLDG");
        Style_com_values.put("4F", "4 FAM");
        Style_com_values.put("50", "PRE-ENG GAR");
        Style_com_values.put("51", "Condo TH");
        Style_com_values.put("52", "Pre-Eng Mfg");
        Style_com_values.put("53", "Pre-Eng Warehs");
        Style_com_values.put("54", "Health Club");
        Style_com_values.put("55", "Condo GR");
        Style_com_values.put("56", "Condo Office");
        Style_com_values.put("57", "Library");
        Style_com_values.put("58", "City/Town Hall");
        Style_com_values.put("59", "Fire Station");
        Style_com_values.put("60", "OFFICE CONDO CONV");
        Style_com_values.put("61", "Dry Cln/Laundr");
        Style_com_values.put("62", "Furn Showroom");
        Style_com_values.put("63", "Antique");
        Style_com_values.put("64", "Tennis Club");
        Style_com_values.put("65", "Skating Arena");
        Style_com_values.put("66", "Hotel");
        Style_com_values.put("67", "Coin-op CarWsh");
        Style_com_values.put("68", "RES TYPE COMM");
        Style_com_values.put("69", "Truck Terminal");
        Style_com_values.put("70", "Dormitory");
        Style_com_values.put("71", "Churches");
        Style_com_values.put("72", "School/College");
        Style_com_values.put("73", "Hospital");
        Style_com_values.put("74", "Assisted Living Fac");
        Style_com_values.put("75", "Post Office");
        Style_com_values.put("76", "Mortuary/Cemet");
        Style_com_values.put("77", "Clubs/Lodges");
        Style_com_values.put("78", "GAS MART");
        Style_com_values.put("79", "Telephone Bldg");
        Style_com_values.put("80", "Stores/Apt Com");
        Style_com_values.put("81", "OFC/APT");
        Style_com_values.put("82", "Auditorium");
        Style_com_values.put("83", "Gymnasium");
        Style_com_values.put("84", "Boarding House");
        Style_com_values.put("85", "OFC OVR RETL");
        Style_com_values.put("86", "Armory");
        Style_com_values.put("87", "Other State");
        Style_com_values.put("88", "Other Federal");
        Style_com_values.put("89", "Other Municip");
        Style_com_values.put("90", "Retail Condo");
        Style_com_values.put("91", "Parking Garage");
        Style_com_values.put("92", "SELF STORAGE");
        Style_com_values.put("93", "Garage/Municipal");
        Style_com_values.put("94", "Outbuildings");
        Style_com_values.put("95", "Garage/Office");
        Style_com_values.put("96", "IND/WHS/OFC");
        Style_com_values.put("97", "High Rise Apt");
        Style_com_values.put("98", "Indust Condo");
        Style_com_values.put("99", "Vacant Land");

        Grade_values.put("", "NONE");
        Grade_values.put("D-", "10");
        Grade_values.put("D", "20");
        Grade_values.put("D+", "30");
        Grade_values.put("C-", "40");
        Grade_values.put("C", "50");
        Grade_values.put("C+", "60");
        Grade_values.put("B-", "70");
        Grade_values.put("B", "80");
        Grade_values.put("B+", "90");
        Grade_values.put("A-", "100");
        Grade_values.put("A", "110");
        Grade_values.put("A+", "120");

//        Story_values.put("1", "100");
//        Story_values.put("1.5", "150");
//        Story_values.put("1.75", "175");
//        Story_values.put("2", "200");
//        Story_values.put("2.5", "250");
//        Story_values.put("2.75", "275");
//        Story_values.put("3", "300");
//        Story_values.put("3.5", "350");
//        Story_values.put("3.75", "375");
//        Story_values.put("4", "400");
//        Story_values.put("5", "500");
//        Story_values.put("6", "600");
//        Story_values.put("7", "700");
//        Story_values.put("8", "800");
//        Story_values.put("9", "900");
//        Story_values.put("10", "1000");

        Roof_Structure_values.put("", "NONE");
        Roof_Structure_values.put("01", "Flat");
        Roof_Structure_values.put("02", "Shed");
        Roof_Structure_values.put("03", "Gable/Hip");
        Roof_Structure_values.put("04", "Wood Truss");
        Roof_Structure_values.put("05", "Salt Box");
        Roof_Structure_values.put("06", "Mansard");
        Roof_Structure_values.put("07", "Gambrel");
        Roof_Structure_values.put("08", "Irregular");
        Roof_Structure_values.put("09", "Rigid Frm/BJst");
        Roof_Structure_values.put("12", "Reinforc Concr");

        Roof_Cover_values.put("", "NONE");
        Roof_Cover_values.put("01", "Metal/Tin");
        Roof_Cover_values.put("02", "Rolled Compos");
        Roof_Cover_values.put("03", "Asphalt");
        Roof_Cover_values.put("04", "Tar & Gravel");
        Roof_Cover_values.put("06", "Asbestos Shing");
        Roof_Cover_values.put("07", "Concrete Tile");
        Roof_Cover_values.put("08", "Clay Tile");
        Roof_Cover_values.put("09", "Enam Mtl Shing");
        Roof_Cover_values.put("10", "Wood Shingle");
        Roof_Cover_values.put("11", "Slate");
        Roof_Cover_values.put("12", "Rubber Memb");

        Heat_Type_values.put("", "NONE");
        Heat_Type_values.put("01", "None");
        Heat_Type_values.put("02", "Floor Furnace");
        Heat_Type_values.put("03", "Hot Air-no Duc");
        Heat_Type_values.put("04", "Forced Air-Duc");
        Heat_Type_values.put("05", "Hot Water");
        Heat_Type_values.put("06", "Steam");
        Heat_Type_values.put("07", "Electr Basebrd");
        Heat_Type_values.put("08", "Radiant");

        Fuel_Type_values.put("", "NONE");
        Fuel_Type_values.put("00", "None");
        Fuel_Type_values.put("01", "Coal or Wood");
        Fuel_Type_values.put("02", "Oil");
        Fuel_Type_values.put("03", "Gas");
        Fuel_Type_values.put("04", "Electric");
        Fuel_Type_values.put("05", "Solar Assisted");

        AC_Type_values.put("", "NONE");
        AC_Type_values.put("01", "None");
        AC_Type_values.put("02", "Heat Pump");
        AC_Type_values.put("03", "Central");
        AC_Type_values.put("04", "Unit/AC");
        AC_Type_values.put("06", "AC & HTG");

        Int_Wall_values.put("", "NONE");
        Int_Wall_values.put("01", "Minim/Masonry");
        Int_Wall_values.put("02", "Wall Brd/Wood");
        Int_Wall_values.put("03", "Plastered");
        Int_Wall_values.put("04", "Plywood Panel");
        Int_Wall_values.put("05", "Drywall/Sheet");
        Int_Wall_values.put("06", "Cust Wd Panel");
        Int_Wall_values.put("07", "K PINE/A WD");
        Int_Wall_values.put("08", "Average");

        Int_Floor_values.put("", "NONE");
        Int_Floor_values.put("01", "Dirt/None");
        Int_Floor_values.put("02", "Minimum/Plywd");
        Int_Floor_values.put("03", "Concr-Finished");
        Int_Floor_values.put("04", "Concr Abv Grad");
        Int_Floor_values.put("05", "Vinyl/Asphalt");
        Int_Floor_values.put("06", "Inlaid Sht Gds");
        Int_Floor_values.put("07", "Cork Tile");
        Int_Floor_values.put("08", "Average");
        Int_Floor_values.put("09", "Pine/Soft Wood");
        Int_Floor_values.put("11", "Ceram Clay Til");
        Int_Floor_values.put("12", "Hardwood");
        Int_Floor_values.put("13", "Parquet");
        Int_Floor_values.put("14", "Carpet");
        Int_Floor_values.put("15", "Quarry Tile");
        Int_Floor_values.put("16", "Terrazzo Epoxy");
        Int_Floor_values.put("17", "Precast Concr");
        Int_Floor_values.put("18", "Slate");
        Int_Floor_values.put("19", "Marble");

        Ext_Wall_res_values.put("", "NONE");
        Ext_Wall_res_values.put("01", "Minimum");
        Ext_Wall_res_values.put("02", "Comp./Wall Brd");
        Ext_Wall_res_values.put("05", "Average");
        Ext_Wall_res_values.put("06", "Board & Batten");
        Ext_Wall_res_values.put("07", "Asbest Shingle");
        Ext_Wall_res_values.put("08", "Wood on Sheath");
        Ext_Wall_res_values.put("09", "Logs");
        Ext_Wall_res_values.put("10", "Above Average");
        Ext_Wall_res_values.put("11", "Clapboard");
        Ext_Wall_res_values.put("12", "Cedar or Redwd");
        Ext_Wall_res_values.put("13", "Pre-Fab Wood");
        Ext_Wall_res_values.put("14", "Wood Shingle");
        Ext_Wall_res_values.put("15", "Concr/Cinder");
        Ext_Wall_res_values.put("16", "Stucco on Wood");
        Ext_Wall_res_values.put("17", "Stucco/Masonry");
        Ext_Wall_res_values.put("18", "Asphalt");
        Ext_Wall_res_values.put("19", "Brick Veneer");
        Ext_Wall_res_values.put("20", "Brick/Masonry");
        Ext_Wall_res_values.put("21", "Stone/Masonry");
        Ext_Wall_res_values.put("23", "Pre-cast Concr");
        Ext_Wall_res_values.put("24", "Reinforc Concr");
        Ext_Wall_res_values.put("25", "Vinyl Siding");
        Ext_Wall_res_values.put("26", "Aluminum Sidng");
        Ext_Wall_res_values.put("27", "Pre-finsh Metl");
        Ext_Wall_res_values.put("28", "Glass/Thermo.");

        Ext_Wall_com_values.put("", "NONE");
        Ext_Wall_com_values.put("01", "NONE");
        Ext_Wall_com_values.put("02", "WOOD FRAME");
        Ext_Wall_com_values.put("03", "MASONRY");
        Ext_Wall_com_values.put("04", "REINF. CONCR");
        Ext_Wall_com_values.put("05", "STEEL");
        Ext_Wall_com_values.put("06", "FIREPRF STEEL");

        Biz_type_com_values.put("", "NONE");
        Biz_type_com_values.put("013C", "PRI RES MDL-94");
        Biz_type_com_values.put("111C", "APT 4-8 MDL 94");
        Biz_type_com_values.put("130", "PRI RES COM");
        Biz_type_com_values.put("310", "PRI COMM");
        Biz_type_com_values.put("901C", "COMM-MASS");
        Biz_type_com_values.put("902C", "COUNTY MDL-94");
        Biz_type_com_values.put("903C", "MUNICPAL  MDL-94");
        Biz_type_com_values.put("904C", "PRI SCHOOL  MDL-94");
        Biz_type_com_values.put("904I", "PRI SCHOOL  MDL-96");
        Biz_type_com_values.put("905C", "P/HOS CHAR  MDL-94");
        Biz_type_com_values.put("905I", "P/HOS CHAR  MDL-96");
        Biz_type_com_values.put("906C", "CHURCH ETC  MDL-94");
        Biz_type_com_values.put("906I", "CHURCH ETC  MDL-96");
        Biz_type_com_values.put("908C", "HSNG AUTH  MDL-94");
        Biz_type_com_values.put("910C", "CHARITABLE  MDL-94");
        Biz_type_com_values.put("920I", "NON PROFIT  MDL-96");
        Biz_type_com_values.put("925C", "COMM MASS MDC");
        Biz_type_com_values.put("925I", "COMM MASS MDC");
        Biz_type_com_values.put("930C", "COMM MASS MBTA");
        Biz_type_com_values.put("955C", "HOSP");
        Biz_type_com_values.put("957C", "CHAR SERV COM");
        Biz_type_com_values.put("960C", "CHURCH");
        Biz_type_com_values.put("961C", "RECTORY");
        Biz_type_com_values.put("1120", "APT OVER 8");
        Biz_type_com_values.put("1210", "BOARDNG HS");
        Biz_type_com_values.put("1250", "OTHR LIV F");
        Biz_type_com_values.put("1400", "CHILD CARE");
        Biz_type_com_values.put("3000", "HOTELS");
        Biz_type_com_values.put("3010", "MOTELS");
        Biz_type_com_values.put("3040", "NURSING HM");
        Biz_type_com_values.put("3050", "HOSP PVT");
        Biz_type_com_values.put("3100", "RTL OIL ST");
        Biz_type_com_values.put("3160", "COMM WHSE");
        Biz_type_com_values.put("3180", "COM GRN HS");
        Biz_type_com_values.put("3210", "HRDWARE ST");
        Biz_type_com_values.put("3220", "STRIP STORES");
        Biz_type_com_values.put("3222", "COMM BLDG");
        Biz_type_com_values.put("3230", "SHOPNG CTR");
        Biz_type_com_values.put("3240", "SUPERMKT");
        Biz_type_com_values.put("3250", "RETAIL");
        Biz_type_com_values.put("3260", "REST/CLUBS");
        Biz_type_com_values.put("3300", "AUTO DEALER");
        Biz_type_com_values.put("3320", "AUTO REPR/GAR");
        Biz_type_com_values.put("3330", "FUEL SV/PR");
        Biz_type_com_values.put("3340", "GAS ST SRV  MDL-95");
        Biz_type_com_values.put("3350", "CAR WASH  MDL-95");
        Biz_type_com_values.put("3360", "PARK GAR");
        Biz_type_com_values.put("3380", "OTH MTR SS");
        Biz_type_com_values.put("3390", "GAS MART");
        Biz_type_com_values.put("3400", "OFFICE BLD");
        Biz_type_com_values.put("3402", "OFFICEBLDG");
        Biz_type_com_values.put("3410", "BANK BLDG");
        Biz_type_com_values.put("3420", "MED OFFC");
        Biz_type_com_values.put("3430", "PROF OFFC");
        Biz_type_com_values.put("3500", "POST OFF");
        Biz_type_com_values.put("3510", "EDUC BLDG");
        Biz_type_com_values.put("3520", "DAY CARE");
        Biz_type_com_values.put("3530", "FRATNL ORG");
        Biz_type_com_values.put("3550", "FUNERAL HM");
        Biz_type_com_values.put("3560", "PROF ASSOC");
        Biz_type_com_values.put("3640", "THEATER");
        Biz_type_com_values.put("3700", "BOWLING");
        Biz_type_com_values.put("3740", "HEALTH SPA");
        Biz_type_com_values.put("3760", "GYMS");
        Biz_type_com_values.put("3800", "GOLF CRSE");
        Biz_type_com_values.put("3810", "TENNIS ODR");
        Biz_type_com_values.put("3840", "MARINAS");
        Biz_type_com_values.put("4000", "INDUSTRIAL");
        Biz_type_com_values.put("4010", "IND WHSES  MDL-96");
        Biz_type_com_values.put("4020", "IND OFFICE");
        Biz_type_com_values.put("4022", "IND BLDG");
        Biz_type_com_values.put("4240", "ELECSUBSTA");
        Biz_type_com_values.put("4300", "TEL X STA");
        Biz_type_com_values.put("4310", "TEL REL TW");
        Biz_type_com_values.put("4330", "RAD/TV TR  MDL-96");
        Biz_type_com_values.put("9000", "US GOVT MDL-94");
        Biz_type_com_values.put("9030", "MUNICPAL  MDL-96");
        Biz_type_com_values.put("9070", "121A CORP");
        Biz_type_com_values.put("9090", "YACHT CLUB");
        Biz_type_com_values.put("9100", "DEPT.ENVIRON.MANGMT");

        Ceiling_com_values.put("", "NONE");
        Ceiling_com_values.put("00", "MINIMAL");
        Ceiling_com_values.put("01", "SUSP-CEIL ONLY");
        Ceiling_com_values.put("02", "CEILING ONLY");
        Ceiling_com_values.put("03", "PT SUSP C+W");
        Ceiling_com_values.put("04", "PT CLNG+WALL");
        Ceiling_com_values.put("05", "SUSP CLNG+WL");
        Ceiling_com_values.put("06", "FIN CLNG+WALL");

        Feature_res_values.put("", "NONE");
        Feature_res_values.put("A/C", "AIR CONDITION");
        Feature_res_values.put("BRN1", "BARN - 1 STORY");
        Feature_res_values.put("BRN3", "1 STORY W/LOFT");
        Feature_res_values.put("BRN5", "2 STORY");
        Feature_res_values.put("BTH1", "BATH HOUSE/CAB");
        Feature_res_values.put("BTH2", "W/PLUMBING");
        Feature_res_values.put("C/V", "CENTRAL VAC");
        Feature_res_values.put("CAB1", "CABIN-MINIMAL");
        Feature_res_values.put("CAB2", "W/PLUMBING ETC");
        Feature_res_values.put("CAN1", "CANOPY");
        Feature_res_values.put("CBN1", "CABANA");
        Feature_res_values.put("CNP1", "CANOPY-AVG");
        Feature_res_values.put("DCK", "DECK");
        Feature_res_values.put("DCK1", "DOCKS-RES TYPE");
        Feature_res_values.put("FCP", "CARPORT");
        Feature_res_values.put("FEP", "ENCLOSED PORCH");
        Feature_res_values.put("FGR1", "GARAGE 1 STY");
        Feature_res_values.put("FGR2", "GARAGE 1.5 STY");
        Feature_res_values.put("FGR3", "GARAGE 2 STY");
        Feature_res_values.put("FGR4", "W/LOFT-AVG");
        Feature_res_values.put("FGR5", "W/LOFT GOOD");
        Feature_res_values.put("FGR7", "PORTBLE GARAGE");
        Feature_res_values.put("FLU1", "FLUE-CONCRETE");
        Feature_res_values.put("FN1", "FENCE-4' CHAIN");
        Feature_res_values.put("FN2", "FENCE-5' CHAIN");
        Feature_res_values.put("FN3", "FENCE-6' CHAIN");
        Feature_res_values.put("FND1", "FOUNDATION");
        Feature_res_values.put("FOP", "OPEN PORCH");
        Feature_res_values.put("FPL", "GAS FIREPLACE");
        Feature_res_values.put("FPL1", "FIREPLACE 1 ST");
        Feature_res_values.put("FPL2", "1.5 STORY CHIM");
        Feature_res_values.put("FPL3", "2 STORY CHIM");
        Feature_res_values.put("FPO", "EXTRA FPL OPEN");
        Feature_res_values.put("GLFP", "GAS LOG FIREPLACE");
        Feature_res_values.put("GRN1", "GREEN HOUSE-RS");
        Feature_res_values.put("HT", "HOT TUB");
        Feature_res_values.put("HT1", "HOTUB");
        Feature_res_values.put("JAC1", "JACUZZI");
        Feature_res_values.put("LNT", "LEAN-TO");
        Feature_res_values.put("MISC", "MISC BLDG");
        Feature_res_values.put("PAT1", "PATIO-AVG");
        Feature_res_values.put("PAT2", "PATIO-GOOD");
        Feature_res_values.put("PAV1", "PAVING-ASPHALT");
        Feature_res_values.put("PAV2", "PAVING-CONC");
        Feature_res_values.put("PE", "PASSNGR ELEV");
        Feature_res_values.put("SHD1", "SHED FRAME");
        Feature_res_values.put("SHD2", "W/LIGHTS ETC");
        Feature_res_values.put("SHD3", "METAL");
        Feature_res_values.put("SHP1", "WORK SHOP AVE");
        Feature_res_values.put("SHP4", "W/IMPROV AGE");
        Feature_res_values.put("SHP5", "W/IMPROV GOOD");
        Feature_res_values.put("SPL1", "POOL-INGR CONC");
        Feature_res_values.put("SPL2", "POOL-INGR VINL");
        Feature_res_values.put("SPL3", "POOL-ING GUNIT");
        Feature_res_values.put("SPL4", "ABOVE GR ROUND");
        Feature_res_values.put("SPL5", "ABOVE GR OVAL");
        Feature_res_values.put("SPL6", "ABOVE GR RECT");
        Feature_res_values.put("SPR1", "SPRINKLERS-WET");
        Feature_res_values.put("SPR2", "WET/CONCEALED");
        Feature_res_values.put("STK2", "CHIMNEY STK MT");
        Feature_res_values.put("TEN", "TENNIS COURT");
        Feature_res_values.put("UBM", "UNFINISHED BASEMENT");
        Feature_res_values.put("WDK", "WOOD DECK AVG");
        Feature_res_values.put("WHL", "WHIRLPOOL");

        Feature_com_values.put("", "NONE");
        Feature_com_values.put("A/C", "AIR CONDITION");
        Feature_com_values.put("ANT", "ANTENNA");
        Feature_com_values.put("ANT1", "ANTENNA");
        Feature_com_values.put("ATM1", "AUTOMATC TELLR");
        Feature_com_values.put("BB", "BILL BOARD");
        Feature_com_values.put("BBHW", "BILL BOARD LARGE");
        Feature_com_values.put("BHS1", "CMM BTH HSE AV");
        Feature_com_values.put("BOX", "SAFE DEPOSIT");
        Feature_com_values.put("BRN1", "BARN - 1 STORY");
        Feature_com_values.put("BRN5", "2 STORY");
        Feature_com_values.put("BTH1", "BATH HOUSE/CAB");
        Feature_com_values.put("CAB2", "W/PLUMBING ETC");
        Feature_com_values.put("CAN1", "CANOPY");
        Feature_com_values.put("CBN1", "CABANA");
        Feature_com_values.put("CLR1", "FREEZER/COOLER");
        Feature_com_values.put("CNP1", "CANOPY-AVG");
        Feature_com_values.put("CNP2", "GOOD QUALITY");
        Feature_com_values.put("DCK", "DECK");
        Feature_com_values.put("DCK1", "DOCKS-RES TYPE");
        Feature_com_values.put("DCK2", "COM TYPE");
        Feature_com_values.put("DCK3", "BOAT DOCK SLIPS");
        Feature_com_values.put("DUW1", "DRIVE-UP WINDW FF");
        Feature_com_values.put("DUW2", "WIDE BAY BANK");
        Feature_com_values.put("DUW3", "W/PNEU TUBE");
        Feature_com_values.put("DUW4", "W/REM SCR&TUBE");
        Feature_com_values.put("FCP", "CARPORT");
        Feature_com_values.put("FE", "FREIGHT ELEV");
        Feature_com_values.put("FEP", "ENCLOSED PORCH");
        Feature_com_values.put("FGR1", "GARAGE 1 STY");
        Feature_com_values.put("FGR2", "GARAGE 1.5 STY");
        Feature_com_values.put("FGR3", "GARAGE 2 STY");
        Feature_com_values.put("FGR4", "W/LOFT-AVG");
        Feature_com_values.put("FGR5", "W/LOFT GOOD");
        Feature_com_values.put("FGR7", "PORTBLE GARAGE");
        Feature_com_values.put("FGR8", "DET CHAPMANS");
        Feature_com_values.put("FLU1", "FLUE-CONCRETE");
        Feature_com_values.put("FN1", "FENCE-4' CHAIN");
        Feature_com_values.put("FN2", "FENCE-5' CHAIN");
        Feature_com_values.put("FN3", "FENCE-6' CHAIN");
        Feature_com_values.put("FN4", "FENCE-8' CHAIN");
        Feature_com_values.put("FN5", "FENCE-10'CHAIN");
        Feature_com_values.put("FN6", "W/O TOP RL-4'");
        Feature_com_values.put("FN7", "W/O TOP RL-5'");
        Feature_com_values.put("FN8", "W/O TOP RL-6'");
        Feature_com_values.put("FN10", "W/O TOP RL-10'");
        Feature_com_values.put("FND1", "FOUNDATION");
        Feature_com_values.put("FOP", "OPEN PORCH");
        Feature_com_values.put("FPL", "GAS FIREPLACE");
        Feature_com_values.put("FPL1", "FIREPLACE 1 ST");
        Feature_com_values.put("FPL2", "1.5 STORY CHIM");
        Feature_com_values.put("FPL3", "2 STORY CHIM");
        Feature_com_values.put("FPO", "EXTRA FPL OPEN");
        Feature_com_values.put("GLFP", "GAS LOG FIREPLACE");
        Feature_com_values.put("GRN1", "GREEN HOUSE-RS");
        Feature_com_values.put("GRN3", "COMM PLASTIC");
        Feature_com_values.put("HT", "HOT TUB");
        Feature_com_values.put("HT1", "HOTUB");
        Feature_com_values.put("KSK1", "KIOSK-SERV STA");
        Feature_com_values.put("KSK3", "BANK KIOSK");
        Feature_com_values.put("LDL1", "LOAD LEVELERS");
        Feature_com_values.put("LDL2", "W/MAN FLIP OUT");
        Feature_com_values.put("LT1", "LIGHTS-IN W/PL");
        Feature_com_values.put("LT2", "W/DOUBLE LIGHT");
        Feature_com_values.put("LT3", "W/TRIPLE LIGHT");
        Feature_com_values.put("LT4", "W/FOUR LIGHTS");
        Feature_com_values.put("LT5", "MERC VAP/FLU");
        Feature_com_values.put("LT6", "W/DOUBLE LIGHT");
        Feature_com_values.put("LT7", "W/TRIPLE LIGHT");
        Feature_com_values.put("LT8", "W/FOUR LIGHTS");
        Feature_com_values.put("LT9", "HGH PRE-SOD PL");
        Feature_com_values.put("LT10", "W/DOUBLE LIGHT");
        Feature_com_values.put("LT11", "W/TRIPLE LIGHT");
        Feature_com_values.put("LT12", "W/FOUR LIGHTS");
        Feature_com_values.put("MEZ1", "MEZZANINE-UNF");
        Feature_com_values.put("MEZ2", "FINISHED");
        Feature_com_values.put("MEZ3", "W/PARTITIONS");
        Feature_com_values.put("MISC", "MISC BLDG");
        Feature_com_values.put("NDP", "NITE DEPOSIT");
        Feature_com_values.put("PAT1", "PATIO-AVG");
        Feature_com_values.put("PAT2", "PATIO-GOOD");
        Feature_com_values.put("PAV1", "PAVING-ASPHALT");
        Feature_com_values.put("PAV2", "PAVING-CONC");
        Feature_com_values.put("PE", "PASSNGR ELEV");
        Feature_com_values.put("PMP1", "PUMP-SING HSE");
        Feature_com_values.put("PMP2", "W/BLENDING");
        Feature_com_values.put("PMP4", "DOUBLE HOSE");
        Feature_com_values.put("PMP5", "W/BLENDING");
        Feature_com_values.put("PMP6", "ELECTRONIC");
        Feature_com_values.put("PMP7", "3 HOSE");
        Feature_com_values.put("RRR", "RAILROAD SPURS");
        Feature_com_values.put("RRS", "RAILROAD SWITCH");
        Feature_com_values.put("SCL2", "SCALES-ELECT");
        Feature_com_values.put("SEA", "SEA WALL");
        Feature_com_values.put("SGN1", "SIGN-1 SD W/M");
        Feature_com_values.put("SGN2", "DOUBLE SIDED");
        Feature_com_values.put("SGN3", "W/INT LIGHTS");
        Feature_com_values.put("SGN4", "W/MOTOR & LTS");
        Feature_com_values.put("SHD1", "SHED FRAME");
        Feature_com_values.put("SHD2", "W/LIGHTS ETC");
        Feature_com_values.put("SHD3", "METAL");
        Feature_com_values.put("SHP1", "WORK SHOP AVE");
        Feature_com_values.put("SHP2", "WORK SHOP GOOD");
        Feature_com_values.put("SLO1", "SILO-WD OR CNC");
        Feature_com_values.put("SPL1", "POOL-INGR CONC");
        Feature_com_values.put("SPL2", "POOL-INGR VINL");
        Feature_com_values.put("SPL3", "POOL-ING GUNIT");
        Feature_com_values.put("SPL4", "ABOVE GR ROUND");
        Feature_com_values.put("SPL5", "ABOVE GR OVAL");
        Feature_com_values.put("SPR1", "SPRINKLERS-WET");
        Feature_com_values.put("SPR2", "WET/CONCEALED");
        Feature_com_values.put("SPR3", "DRY");
        Feature_com_values.put("TEN", "TENNIS COURT");
        Feature_com_values.put("TNK1", "TANK-UNDERGRND");
        Feature_com_values.put("TNK3", "GT-10,000");
        Feature_com_values.put("TNK5", "ELEVATED TANK");
        Feature_com_values.put("UBM", "UNFINISHED BASEMENT");
        Feature_com_values.put("ULP", "UNFIN LOADING PLATFORM");
        Feature_com_values.put("VLT1", "VAULT-AVG");
        Feature_com_values.put("VLT2", "VAULT-GOOD");
        Feature_com_values.put("WDK", "WOOD DECK AVG");

        Feature_cond_values.put("", "NONE");
        Feature_cond_values.put("A/C", "AIR CONDITION");
        Feature_cond_values.put("C/V", "CENTRAL VAC");
        Feature_cond_values.put("DCK", "DECK");
        Feature_cond_values.put("DCK1", "DOCKS-RES TYPE");
        Feature_cond_values.put("FCP", "CARPORT");
        Feature_cond_values.put("FEP", "ENCLOSED PORCH");
        Feature_cond_values.put("FGR1", "GARAGE 1 STY");
        Feature_cond_values.put("FGR2", "GARAGE 1.5 STY");
        Feature_cond_values.put("FGR3", "GARAGE 2 STY");
        Feature_cond_values.put("FGR4", "W/LOFT-AVG");
        Feature_cond_values.put("FGR5", "W/LOFT GOOD");
        Feature_cond_values.put("FGR7", "PORTBLE GARAGE");
        Feature_cond_values.put("FLU1", "FLUE-CONCRETE");
        Feature_cond_values.put("FOP", "OPEN PORCH");
        Feature_cond_values.put("FPL", "GAS FIREPLACE");
        Feature_cond_values.put("FPL1", "FIREPLACE 1 ST");
        Feature_cond_values.put("FPL2", "1.5 STORY CHIM");
        Feature_cond_values.put("FPL3", "2 STORY CHIM");
        Feature_cond_values.put("FPO", "EXTRA FPL OPEN");
        Feature_cond_values.put("GLFP", "GAS LOG FIREPLACE");
        Feature_cond_values.put("GRN1", "GREEN HOUSE-RS");
        Feature_cond_values.put("HT", "HOT TUB");
        Feature_cond_values.put("HT1", "HOTUB");
        Feature_cond_values.put("JAC1", "JACUZZI");
        Feature_cond_values.put("LNT", "LEAN-TO");
        Feature_cond_values.put("MISC", "MISC BLDG");
        Feature_cond_values.put("PAT1", "PATIO-AVG");
        Feature_cond_values.put("PAT2", "PATIO-GOOD");
        Feature_cond_values.put("PE", "PASSNGR ELEV");
        Feature_cond_values.put("SHD1", "SHED FRAME");
        Feature_cond_values.put("SHD2", "W/LIGHTS ETC");
        Feature_cond_values.put("SHD3", "METAL");
        Feature_cond_values.put("SPR1", "SPRINKLERS-WET");
        Feature_cond_values.put("SPR2", "WET/CONCEALED");
        Feature_cond_values.put("UBM", "UNFINISHED BASEMENT");
        Feature_cond_values.put("WDK", "WOOD DECK AVG");
        Feature_cond_values.put("WHL", "WHIRLPOOL");

        Kitchen_values.put("", "NONE");
        Kitchen_values.put("01", "Orig");
        Kitchen_values.put("02", "S-Modern");
        Kitchen_values.put("03", "Modern");

        Bath_values.put("", "NONE");
        Bath_values.put("01", "Old Style");
        Bath_values.put("02", "Average");
        Bath_values.put("03", "Modern");

        Floor_values.put("", "NONE");
        Floor_values.put("01", "Dirt/None");
        Floor_values.put("02", "Minimum/Plywd");
        Floor_values.put("03", "Concr-Finished");
        Floor_values.put("04", "Concr Abv Grad");
        Floor_values.put("05", "Vinyl/Asphalt");
        Floor_values.put("06", "Inlaid Sht Gds");
        Floor_values.put("07", "Cork Tile");
        Floor_values.put("08", "Average");
        Floor_values.put("09", "Pine/Soft Wood");
        Floor_values.put("11", "Ceram Clay Til");
        Floor_values.put("12", "Hardwood");
        Floor_values.put("13", "Parquet");
        Floor_values.put("14", "Carpet");
        Floor_values.put("15", "Quarry Tile");
        Floor_values.put("16", "Terrazzo Epoxy");
        Floor_values.put("17", "Precast Concr");
        Floor_values.put("18", "Slate");
        Floor_values.put("19", "Marble");

    }

}
